### ISSUE TITLE
Version 05.00.00 Release Tasks

### ISSUE THREAD

**Issue by hismightiness** [DNNCommunity/DNN.Media#15]
The following tasks need to be done in order to consider the release to be complete:

- [x] Version number update in project settings
- [x] Version number update in manifest
- [x] SqlDataProvider file
- [x] Copyright year in source files
- [x] Copyright year in License.txt
- [x] Create clean up file
- [x] Update release notes
- [x] Create Install/Source packages
- [x] Create Symbols package
- [x] [EVS validation](http://evs.dnnsoftware.com/)
- [x] Final developer testing
- [x] Pull request/merge
- [x] Add packages to [GitHub](https://github.com/DNNCommunity/DNN.Media/releases)
- [x] Update the [DNN Forge](http://www.dnnsoftware.com/forge)
- [x] Announce on [DNN Software forums](http://www.dnnsoftware.com/forums/forumid/112/scope/threads)
- [x] Announce on Facebook, G+, Twitter

**Comment by EPTamminga** [comment]
This is a nice general checklist for finishing any new module release...
